apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lb-routing-fix
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lb-routing-fix
subjects:
- kind: ServiceAccount
  namespace: kube-system
  name: lb-routing-fix
