apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: lb-routing-fix
  namespace: kube-system
spec:
  schedule: "20 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: lb-routing-fix
          automountServiceAccountToken: yes
          containers:
          - name: lb-routing-fix
            image: jtalk/kube-proxy-load-balancer-fix:[[IMAGE_TAG]]
            args:
            - 159.65.209.138
          restartPolicy: Never
