apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lb-routing-fix
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - get
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
