name: Deploy to Kubernetes

on: [push]

env:
  DOCKER_IMAGE_PREFIX: jtalk/kube-proxy-load-balancer-fix
  DOCKER_IMAGE: jtalk/kube-proxy-load-balancer-fix:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Image
      run: docker build -t ${{ env.DOCKER_IMAGE }} .
    - name: Docker Login
      if: github.ref == 'refs/heads/master'
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Deploy image
      if: github.ref == 'refs/heads/master'
      run: docker push ${{ env.DOCKER_IMAGE }}
