name: Deploy to Kubernetes

on: [push]

env:
  DOCKER_IMAGE_PREFIX: jtalk/kube-proxy-load-balancer-fix
  DOCKER_IMAGE: jtalk/kube-proxy-load-balancer-fix:${{ github.sha }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Image
      run: docker build -t ${{ env.DOCKER_IMAGE }} .
    - name: Docker Login
      if: github.ref == 'refs/heads/master'
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Deploy image
      if: github.ref == 'refs/heads/master'
      run: docker push ${{ env.DOCKER_IMAGE }}
      
  deploy: 
    name: Deploy the daily cleanup job for the staging cluster
    runs-on: ubuntu-latest
    needs: [build-push]
    if: github.ref == 'refs/heads/master'
    env:
      KUBECONFIG: ${{ github.workspace }}/.kubeconfig
    steps:
      - uses: actions/checkout@v1
      - name: Load Kubernetes config
        uses: digitalocean/action-doctl@v1.8.0
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DO_TOKEN }}
        with:
          args: kubernetes cluster kubeconfig show ${{ secrets.DO_CLUSTER_NAME }} > $GITHUB_WORKSPACE/.kubeconfig
      - name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v1
        with:
          namespace: kube-system
          kubectl-version: v1.17.0
          manifests: |
            deploy/lb-fix.cronjob.yaml
            deploy/lb-fix.role.yaml
            deploy/lb-fix.rolebinding.yaml
            deploy/lb-fix.serviceaccount.yaml
          images: ${{ env.DOCKER_IMAGE }}
          
